add bash completion file
projg2/pycargoebuild pull request #26
Opened 2024-06-06 19:19 UTC by arthurzam

2024-06-10 18:32 UTC, antecrescent commented
The typing CI issue (https://github.com/python/typeshed/issues/11072) was fixed incorrectly upstream. I opened a new issue at https://github.com/python/typeshed/issues/12127.

To temporarily silence this issue until it is fixed upstream, you could cast `preset`:
```diff
diff --git a/pycargoebuild/__main__.py b/pycargoebuild/__main__.py
index 91a38c5..b60c702 100644
--- a/pycargoebuild/__main__.py
+++ b/pycargoebuild/__main__.py
@@ -333,7 +333,9 @@ def main(prog_name: str, *argv: str) -> int:
                                   mode="w:xz",
                                   format=tarfile.GNU_FORMAT,
                                   encoding="UTF-8",
-                                  preset=9 | lzma.PRESET_EXTREME,
+                                  preset=typing.cast(
+                                      typing.Optional[typing.Listing[0,1,2,3,4,5,6,7,8,9]],
+                                      9 | lzma.PRESET_EXTREME),
                                   ) as tar_out:  # type: ignore
                     os.fchmod(cratef.fileno(), 0o666 & ~umask)
                     logging.info("Repacking crates ...")
```

2024-06-10 19:56 UTC, antecrescent reviewed
Had a look at the code and tested it locally for a bit, LGTM. I have one question, though. Why did you add a new wheel and sdist for the previous release to the `dist` directory? I didn't find anything related to it in the code and I don't think that re-releasing 0.13.2 is what you are going for. What am I missing? :)

2024-06-10 19:58 UTC, arthurzam commented
> Had a look at the code and tested it locally for a bit, LGTM. I have on question, though. Why did you add a new wheel and sdist for the previous release to the `dist` directory? I didn't find anything related to it in the code and I don't think that re-releasing 0.13.2 is what you are going for. What am I missing? :)

I didn't notice that - a mistake, lol. Should be in gitignore, lol.

2024-06-12 14:28 UTC, mgorny requested changes

2024-06-12 14:28 UTC, mgorny commented on data/share/bash-completion/completions/pycargoebuild
> +# Copyright 2024 Gentoo Authors
Just put yourself here, "Gentoo Authors" outside Gentoo is pretty indeterminate.

2024-06-12 14:28 UTC, mgorny commented on data/share/bash-completion/completions/pycargoebuild
> +# Distributed under the terms of the GNU General Public License, v2 or later
…and use the SPDX thingy, for consistency.

2024-06-12 16:53 UTC, mgorny commented on .gitignore
> +*.tar.gz
```suggestion
/dist/
```

?

2024-07-02 06:27 UTC, mgorny approved these changes
LGTM, thanks!

2024-07-02 06:28 UTC, closed without merging